language: node_js
node_js: node
before_deploy:
- openssl aes-256-cbc -K $encrypted_1149f0312a8d_key -iv $encrypted_1149f0312a8d_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_key
- ssh-add .travis/deploy_key
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
